---
Attribute:
  enabled: true
  exclude:
  - SQL::Generator::Emitter
  - SQL::Generator::Stream
BooleanParameter:
  enabled: true
  exclude: []
ClassVariable:
  enabled: true
  exclude:
  - SQL::Generator::Emitter
ControlParameter:
  enabled: true
  exclude: []
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: true
  exclude:
   - SQL::Generator::Emitter#indented
   - SQL::Generator::Emitter::BinaryInfixOperation#dispatch
   - SQL::Generator::Emitter::Delete#dispatch
   - SQL::Generator::Emitter::Select#dispatch
   - SQL::Generator::Emitter::Update#dispatch
   - SQL::Generator::Stream::Indented#<<
  max_calls: 1
  allow_calls: []
FeatureEnvy:
  enabled: true
  exclude:
  - SQL::UnknownTypeError#initialize
IrresponsibleModule:
  enabled: true
  exclude: []
LongParameterList:
  enabled: true
  exclude:
  - SQL::Generator::Emitter::DSL#visit
  max_params: 2
  overrides:
    initialize:
      max_params: 3
LongYieldList:
  enabled: true
  exclude: []
  max_params: 2
NestedIterators:
  enabled: true
  exclude:
  - SQL::Generator::Emitter#self.children  # metaprogramming
  - SQL::Generator::Emitter::Set#dispatch  # parenthesis inside a loop
  max_allowed_nesting: 1
  ignore_iterators: []
NilCheck:
  enabled: true
  exclude: []
RepeatedConditional:
  enabled: true
  exclude: []
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  exclude:
  - SQL::Generator::Emitter  # incorrectly counts class ivar
  max_instance_variables: 3
TooManyMethods:
  enabled: true
  exclude: []
  max_methods: 10
TooManyStatements:
  enabled: true
  max_statements: 7
UncommunicativeMethodName:
  enabled: true
  exclude:
  - SQL::NodeHelper#s
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  exclude:
  - SQL::NodeHelper#s
  - SQL::UnknownTypeError#initialize
  max_helper_calls: 0
